### ISSUE TITLE
feature request: Add custom classes to the buttons

### ISSUE THREAD

**Issue by nicdim** [dfactoryplugins/cookie-notice#28]
A feature request: 
To have the ability to enter additional class names in wp-admin, to be added to the <a> class attribute for the buttons in the cookie notice banner.
These can be added in addition to the current css styles:  none/wordpress/bootstrap

I've already made the modifications necessary but can't seem to create a pull request to submit my changes.  Would you like my contribution?  (changes to file: cookie-notice.php)

**Comment by bartoszarendt** [comment]
Done in recent release.
