### ISSUE TITLE
Bug: Not compatible with Slider Revolution / Revslider

### ISSUE THREAD

**Issue by ginsterbusch** [dfactoryplugins/cookie-notice#31]
When having a revslider-Slideshow sitting prominently at the start / top of the page, esp. the home page, the notice is not being displayed **AT ALL!**

Personally I guess its either an issue with the z-index, very late post-loading of the slideshow images, or even veeery late priority for the slideshow JS / CSS assets.

If you aint been stumbling over this issue before, I might even go as far and fix this issue myself (and drop a pull request onto you) ;)

Issue appears both with RevSlider 5.0, 5.3 and 5.4.

cu, w0lf.

**Comment by bartoszarendt** [comment]
Just adjust the z-index of the slider to a lower value using custom CSS.

**Comment by ginsterbusch** [comment]
Well ..  guess I gonna do the PR thingy. Because out of the box support is much better AND will calm down customers ..
